services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: poacher_detection
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - pip-cache:/root/.cache/pip
    depends_on:
      - postgres
      - redis
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
        - DATABASE_URL=postgresql://user:password@postgres:5432/poacher_detection
        - PYTHONDONTWRITEBYTECODE=1
        - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
    working_dir: /app
    command: npm start
    environment:
        - CHOKIDAR_USEPOLLING=true  # Fixes hot reload on some hosts

volumes:
  pip-cache:
  frontend_node_modules:
